import wmill
import json
import requests

def main(body: dict = None) -> dict:
    """
    Complete Telegram bot webhook handler for movie mood generation
    """
    
    try:
        print(f"Received Telegram webhook: {json.dumps(body, indent=2)}")
        print(f"Body type: {type(body)}")
        
        # Handle null/None body
        if body is None:
            print("Body is None - no data received from Telegram")
            return {"status": "no_data", "error": "No webhook data received"}
        
        # Handle non-dict body (sometimes comes as string)
        if not isinstance(body, dict):
            print(f"Body is not dict, trying to parse: {body}")
            try:
                if isinstance(body, str):
                    body = json.loads(body)
                else:
                    return {"status": "invalid_format", "error": f"Body is {type(body)}, expected dict"}
            except json.JSONDecodeError as e:
                return {"status": "json_error", "error": f"Could not parse body as JSON: {str(e)}"}
        
        # Extract message details from Telegram update
        if 'message' not in body:
            print(f"No 'message' key in body. Keys: {list(body.keys()) if body else 'None'}")
            return {"status": "no_message", "response": "No message in update", "body_keys": list(body.keys()) if body else None}
        
        message = body['message']
        chat_id = message['chat']['id']
        
        # Check if message has text
        if 'text' not in message:
            return send_telegram_message(
                chat_id, 
                "🎬 Please send me a movie title and I'll tell you the mood words for it!"
            )
        
        text = message['text'].strip()
        print(f"Processing message: '{text}' from chat_id: {chat_id}")
        
        # Handle commands
        if text.startswith('/'):
            if text.lower() in ['/start', '/help']:
                welcome_message = (
                    "🎬 *Movie Mood Generator Bot* 🎭\n\n"
                    "Send me any movie title and I'll generate mood words that describe it!\n\n"
                    "*Examples:*\n"
                    "• Inception\n"
                    "• The Dark Knight\n"
                    "• Pulp Fiction\n"
                    "• Star Wars\n\n"
                    "Just type the movie name - no commands needed! ✨"
                )
                return send_telegram_message(chat_id, welcome_message, parse_mode="Markdown")
            else:
                return send_telegram_message(
                    chat_id, 
                    "🤔 Unknown command. Just send me a movie title!"
                )
        
        # If empty message
        if not text:
            return send_telegram_message(
                chat_id, 
                "🎬 Please send me a movie title!"
            )
        
        # Generate mood words for the movie
        print(f"Generating moods for movie: {text}")
        mood_result = generate_movie_moods(text)
        
        # Format response based on success/failure
        if mood_result.get('success', False):
            response_text = (
                f"🎬 *{mood_result['movie']}*\n\n"
                f"🎭 **Mood Words:** {mood_result['moods']}\n\n"
                f"✨ _Generated by {mood_result.get('model_used', 'AI')}_"
            )
            parse_mode = "Markdown"
        else:
            error_msg = mood_result.get('error', 'Unknown error occurred')
            response_text = (
                f"❌ Sorry, I couldn't generate mood words for '{text}'\n\n"
                f"Error: {error_msg}\n\n"
                f"Please try again with another movie title! 🎬"
            )
            parse_mode = None
        
        # Send response back to user
        return send_telegram_message(chat_id, response_text, parse_mode=parse_mode)
        
    except Exception as e:
        print(f"Error in telegram bot handler: {str(e)}")
        # Try to send error message to user if possible
        try:
            if body and isinstance(body, dict) and 'message' in body and 'chat' in body['message']:
                chat_id = body['message']['chat']['id']
                return send_telegram_message(
                    chat_id, 
                    f"🚨 Oops! Something went wrong. Please try again later.\n\nError: {str(e)}"
                )
        except:
            pass  # If we can't even send error message, just return error status
        
        return {
            "status": "error", 
            "error": str(e),
            "update_received": body,
            "body_type": str(type(body))
        }


def generate_movie_moods(movie_title: str) -> dict:
    """
    Generate mood words for a movie using OpenRouter API
    """
    
    # Get OpenRouter API key from Windmill resource
    api_key = None
    
    try:
        # Get OpenRouter resource - try different paths silently
        openrouter_resource = None
        for resource_path in ["u/philipgalebach/thinner_openrouter", "philipgalebach/thinner_openrouter"]:
            try:
                openrouter_resource = wmill.get_resource(resource_path)
                break  # Found it, stop trying
            except:
                continue  # Try next path
        # Handle both string and dict resource formats
        if openrouter_resource:
            if isinstance(openrouter_resource, dict):
                api_key = openrouter_resource.get("api_key")
            else:
                api_key = openrouter_resource
    except Exception:
        pass  # wmill might not be available in local testing
    
    if not api_key:
        return {
            "movie": movie_title,
            "error": "OpenRouter API key not found. Please check Windmill resource configuration.",
            "success": False
        }
    
    # Simple prompt for mood generation
    prompt = f"Generate 3-5 mood words that describe the movie '{movie_title}'. Return only the mood words separated by commas. Examples: Dark, Mysterious, Intense, Complex, Thought-provoking"
    
    try:
        # Make OpenRouter API call
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "https://windmill.dev",  # Optional. Site URL for rankings
                "X-Title": "Windmill Movie Mood Generator",  # Optional. Site title for rankings
            },
            data=json.dumps({
                "model": "google/gemini-2.0-flash-lite-001",  # Using the model from your example
                "messages": [
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "max_tokens": 100,
                "temperature": 0.7
            })
        )
        
        # Check if request was successful
        response.raise_for_status()
        
        # Parse response
        response_data = response.json()
        moods = response_data['choices'][0]['message']['content'].strip()
        
        return {
            "movie": movie_title,
            "moods": moods,
            "model_used": "google/gemini-2.0-flash-lite-001",
            "success": True
        }
        
    except requests.exceptions.RequestException as e:
        return {
            "movie": movie_title,
            "error": f"Request error: {str(e)}",
            "success": False
        }
    except KeyError as e:
        return {
            "movie": movie_title,
            "error": f"Response parsing error: {str(e)}",
            "response": response.text if 'response' in locals() else "No response",
            "success": False
        }
    except Exception as e:
        return {
            "movie": movie_title,
            "error": f"Unexpected error: {str(e)}",
            "success": False
        }


def send_telegram_message(chat_id: int, text: str, parse_mode: str = None) -> dict:
    """
    Send a message via Telegram bot
    """
    
    try:
        # Get Telegram resource
        telegram_auth = wmill.get_resource("u/philipgalebach/windmill_telegram_test2_bot")
        
        # Handle both string and dict resource formats
        if isinstance(telegram_auth, dict):
            bot_token = telegram_auth.get("token")
            if not bot_token:
                # Try different key names
                for key in ["bot_token", "api_token", "value"]:
                    if key in telegram_auth:
                        bot_token = telegram_auth[key]
                        break
        else:
            bot_token = telegram_auth
        
        if not bot_token:
            print("Failed to get Telegram bot token from resource")
            return {
                "status": "token_error",
                "error": "Bot token not found in resource",
                "chat_id": chat_id
            }
        
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        
        payload = {
            "chat_id": chat_id,
            "text": text
        }
        
        if parse_mode:
            payload["parse_mode"] = parse_mode
        
        response = requests.post(url, json=payload)
        response.raise_for_status()
        
        return {
            "status": "message_sent",
            "response": response.json(),
            "chat_id": chat_id,
            "text_length": len(text)
        }
        
    except requests.exceptions.RequestException as e:
        print(f"Failed to send Telegram message: {str(e)}")
        return {
            "status": "send_failed",
            "error": str(e),
            "chat_id": chat_id
        }
    except Exception as e:
        print(f"Unexpected error sending message: {str(e)}")
        return {
            "status": "unexpected_error",
            "error": str(e),
            "chat_id": chat_id
        }
